//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autobazar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("autobazar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find requested file, created new.
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_ConnectionNewFile {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_ConnectionNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is Ok.
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_ConnectionOk {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_ConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Id of car which you want to delete or write exit to leave..
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_DeleteWelcome {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_DeleteWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_Goodbye {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Id of car which you want to update or type exit to leave..
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_UpdateWelcome {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_UpdateWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Autobazar.{0}To see all cars press 0.{1}To add new car press 1.{2}To remove a car press 2.{3}To update information about car press 3.{4}To exit press 4..
        /// </summary>
        internal static string AutobazarManager_RunTheAutobazar_Welcome {
            get {
                return ResourceManager.GetString("AutobazarManager_RunTheAutobazar_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change the brand of car? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_CarBrand {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change the type of car? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_CarType {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change number of doors? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Doors {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change the type of fuel? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Fuel {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change if car was in an accident? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_IsCarCrashed {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_IsCarCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change number of kilometers? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Kilometers {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change price? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Price {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change town for selling the car? Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Town {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to change vintage?  Yes: 0, No: 1.
        /// </summary>
        internal static string BazarManager_ChangeCarProperty_Vintage {
            get {
                return ResourceManager.GetString("BazarManager_ChangeCarProperty_Vintage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input, please try again.
        /// </summary>
        internal static string BazarManager_ParseMethods_WrongInput {
            get {
                return ResourceManager.GetString("BazarManager_ParseMethods_WrongInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the car ever been in the accident? true: 1, false: 2.
        /// </summary>
        internal static string BazarManager_ParseStringToBool_IsTheCrashed {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToBool_IsTheCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Car Brand of your car or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToEnum_CarBrand {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToEnum_CarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Car Type or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToEnum_CarType {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToEnum_CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Type Of Fuel or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToEnum_Fuel {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToEnum_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select town where the car is going to be sell or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToEnum_Town {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToEnum_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert number of doors or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToInt_Doors {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToInt_Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert number kilometers your car was used or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToInt_Kilometers {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToInt_Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Price or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToInt_Price {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToInt_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert number of Vintage or type exit to leave..
        /// </summary>
        internal static string BazarManager_ParseStringToInt_Vintage {
            get {
                return ResourceManager.GetString("BazarManager_ParseStringToInt_Vintage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no cars in the database.
        /// </summary>
        internal static string BazarManager_ShowAllCars_EmptyDb {
            get {
                return ResourceManager.GetString("BazarManager_ShowAllCars_EmptyDb", resourceCulture);
            }
        }
    }
}
